### ISSUE TITLE
Adding ability to only run certain percentage of requests 

### ISSUE THREAD

**Issue by mdevine82** [staabm/xhprof.io#33]
Use what XHGui is using as well as what's in the original XHProf project.  Could probably just add something like this into the config file.  Useful when you want to run this profiling in a production environment.

    if(rand(0,100) == 42) {
      //Run profiler
    }

**Comment by staabm** [comment]
This is already possible using a `xhprof.inc.php` placed within the app beeing profilled.
We search this file like apache searches for a `.htaccess` all the tree up.

It just needs to contain something like

```php
return array(
  'enabled` => rand(1, 100) == 42,
  // ...
);
```
