### ISSUE TITLE
Enable CLI  processing

### ISSUE THREAD

**Issue by mdevine82** [staabm/xhprof.io#34]
Right now CLI processing isn't enabled because the project is using some of the HTTP server globals to build up the data model.  So here are some of my initial thoughts for replacements.

We do a check to see if its a CLI script and if so
* Make 'method' = CRON
* Make 'uri' = Fetch the script run name and possibly the args used and append them to a URI
* Make 'host' = This one I could see going a few different ways.  Either we could use the systems hostname or have some sort of set value from the config file maybe

**Comment by staabm** [comment]
As pointed out in https://github.com/gajus/xhprof.io/issues/63 a PR adding cli support is very welcome.

The host could be filled by the nodename provided by http://php.net/manual/en/function.posix-uname.php

**Comment by staabm** [comment]
fixed in https://github.com/staabm/xhprof.io/pull/35
