### ISSUE TITLE
What is min memory requirement of xhprof.io? 

### ISSUE THREAD

**Issue by tkyeung357** [staabm/xhprof.io#39]
I install xhprof.io to my dev box (aws ec2) and trigger below General Error 1442: 

> Type:		PDOException
Message:	SQLSTATE[HY000]: General error: 1114 The table 'temporary_request_data' is full
File:		[xhprof.io]/xhprof/classes/data.php
Line:		542
Time:		Mar 3, 2017 04:58

**Comment by staabm** [comment]
not sure what you are asking for. the error message tells me that your mysql table is full?

I never ran into this problem before with mysql default settings.

**Comment by tkyeung357** [comment]
yes. thats why i would like to know the min/suggested system requirement  (2G or 4G RAM?) to for xhprof.io  because i am testing the xhprof UI on my dev box (AWS EC2, 1cpu, 0.5G RAM, ubuntu 12.04, php5.3, mysql 5.6) and only error message displayed. 

sorry for my poor english! i just want to know how large scale upgrade i need to do to support xhprof.io.






On March 3, 2017 at 3:56:33 PM, Markus Staab (notifications@github.com) wrote:

not sure what you are asking for. the error message tells me that your mysql table is full?

**Comment by staabm** [comment]
the problem you encounter depends on a mysql setting for temp tables... I dont think you would need a RAM upgrade (at worst mysql will swap).

I would propose you should try the tool on local/low-cost host at first in case you are evaluting the tool right now.
